export const SET_TYPING_VALUE = "SET_TYPING_VALUE";

//Fetch/Axios
export const ITEMS_HAS_ERRORED = "ITEMS_HAS_ERRORED";
export const ITEMS_IS_LOADING = "ITEMS_IS_LOADING";
export const RESET_FIELDS = "RESET_FIELDS";
export const CITY_FETCH_DATA_SUCCESS = "CITY_FETCH_DATA_SUCCESS";
export const ID_FETCH_DATA_SUCCESS = "ID_FETCH_DATA_SUCCESS";

//Sorting
export const SORT_BY_TEMP_ASC = "SORT_BY_TEMP_ASC";
export const SORT_BY_TEMP_DESC = "SORT_BY_TEMP_DESC";
export const SORT_BY_WIND_ASC = "SORT_BY_WIND_ASC";
export const SORT_BY_WIND_DESC = "SORT_BY_WIND_DESC";
export const SORT_BY_HUMIDITY_ASC = "SORT_BY_HUMIDITY_ASC";
export const SORT_BY_HUMIDITY_DESC = "SORT_BY_HUMIDITY_DESC";
export const SORT_BY_CLOUDS_ASC = "SORT_BY_CLOUDS_ASC";
export const SORT_BY_CLOUDS_DESC = "SORT_BY_CLOUDS_DESC";
